language: cpp

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - cmake-data
            - gcc-6.2

install:
    - export GTESTDIR="${TRAVIS_BUILD_DIR}/build-gtest"
    - export GTEST_ROOT="${GTESTDIR}/googletest-release-1.7.0"
    - cd "${TRAVIS_BUILD_DIR}"
    - chmod +x .travis-dependencies.sh
    - ./.travis-dependencies.sh

script:
    - mkdir build
    - cd build
    - cmake .. && make && ctest -V

cache:
    directories:
        - build-gtest
