#ifndef OPTIONS_H
#define OPTIONS_H

#define RENDER_TERMINAL
#define RENDER_LCD
#define RENDER_SEVEN_SEGMENT
#define CONTROLS_TERMINAL
#define CONTROLS_NUNCHUCK
#define CONTROLS_TOUCH

#endif /* GAME_OPTIONS_H */
